#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ORM_STM;


namespace ORM_STM	
{
	public partial class Bu
	{
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private DateTime? _fecha_Adq;
		public virtual DateTime? Fecha_adq 
		{ 
		    get
		    {
		        return this._fecha_Adq;
		    }
		    set
		    {
		        this._fecha_Adq = value;
		    }
		}
		
		private string _modelo;
		public virtual string Modelo 
		{ 
		    get
		    {
		        return this._modelo;
		    }
		    set
		    {
		        this._modelo = value;
		    }
		}
		
		private string _placa;
		public virtual string Placa 
		{ 
		    get
		    {
		        return this._placa;
		    }
		    set
		    {
		        this._placa = value;
		    }
		}
		
		private string _tipo;
		public virtual string Tipo 
		{ 
		    get
		    {
		        return this._tipo;
		    }
		    set
		    {
		        this._tipo = value;
		    }
		}
		
		private string _color;
		public virtual string Color 
		{ 
		    get
		    {
		        return this._color;
		    }
		    set
		    {
		        this._color = value;
		    }
		}
		
		private string _fabricante;
		public virtual string Fabricante 
		{ 
		    get
		    {
		        return this._fabricante;
		    }
		    set
		    {
		        this._fabricante = value;
		    }
		}
		
		private string _capacidad;
		public virtual string Capacidad 
		{ 
		    get
		    {
		        return this._capacidad;
		    }
		    set
		    {
		        this._capacidad = value;
		    }
		}
		
		private string _tipo_Combust;
		public virtual string Tipo_combust 
		{ 
		    get
		    {
		        return this._tipo_Combust;
		    }
		    set
		    {
		        this._tipo_Combust = value;
		    }
		}
		
		private bool? _estado;
		public virtual bool? Estado 
		{ 
		    get
		    {
		        return this._estado;
		    }
		    set
		    {
		        this._estado = value;
		    }
		}
		
		private IList<Programacion> _programacions = new List<Programacion>();
		public virtual IList<Programacion> Programacions 
		{ 
		    get
		    {
		        return this._programacions;
		    }
		}
		
	}
}
