#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ORM_STM;


namespace ORM_STM	
{
	public partial class Estacion
	{
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private string _nombre;
		public virtual string Nombre 
		{ 
		    get
		    {
		        return this._nombre;
		    }
		    set
		    {
		        this._nombre = value;
		    }
		}
		
		private string _direccion;
		public virtual string Direccion 
		{ 
		    get
		    {
		        return this._direccion;
		    }
		    set
		    {
		        this._direccion = value;
		    }
		}
		
		private bool? _estado;
		public virtual bool? Estado 
		{ 
		    get
		    {
		        return this._estado;
		    }
		    set
		    {
		        this._estado = value;
		    }
		}
		
		private IList<Tarjetum> _tarjeta = new List<Tarjetum>();
		public virtual IList<Tarjetum> Tarjeta 
		{ 
		    get
		    {
		        return this._tarjeta;
		    }
		}
		
		private IList<Solicitud_reclamo> _solicitud_Reclamos = new List<Solicitud_reclamo>();
		public virtual IList<Solicitud_reclamo> Solicitud_reclamos 
		{ 
		    get
		    {
		        return this._solicitud_Reclamos;
		    }
		}
		
		private IList<Recarga> _recargas = new List<Recarga>();
		public virtual IList<Recarga> Recargas 
		{ 
		    get
		    {
		        return this._recargas;
		    }
		}
		
		private IList<Empleado> _empleados = new List<Empleado>();
		public virtual IList<Empleado> Empleados 
		{ 
		    get
		    {
		        return this._empleados;
		    }
		}
		
		private IList<Consumo> _consumos = new List<Consumo>();
		public virtual IList<Consumo> Consumos 
		{ 
		    get
		    {
		        return this._consumos;
		    }
		}
		
	}
}
