#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ORM_STM;


namespace ORM_STM	
{
	public partial class Programacion
	{
		private int _id_Bus;
		public virtual int Id_bus 
		{ 
		    get
		    {
		        return this._id_Bus;
		    }
		    set
		    {
		        this._id_Bus = value;
		    }
		}
		
		private int _id_Ruta;
		public virtual int Id_ruta 
		{ 
		    get
		    {
		        return this._id_Ruta;
		    }
		    set
		    {
		        this._id_Ruta = value;
		    }
		}
		
		private int _id_Empleado;
		public virtual int Id_empleado 
		{ 
		    get
		    {
		        return this._id_Empleado;
		    }
		    set
		    {
		        this._id_Empleado = value;
		    }
		}
		
		private DateTime? _fecha;
		public virtual DateTime? Fecha 
		{ 
		    get
		    {
		        return this._fecha;
		    }
		    set
		    {
		        this._fecha = value;
		    }
		}
		
		private string _horario;
		public virtual string Horario 
		{ 
		    get
		    {
		        return this._horario;
		    }
		    set
		    {
		        this._horario = value;
		    }
		}
		
		private Bu _bu;
		public virtual Bu Bu 
		{ 
		    get
		    {
		        return this._bu;
		    }
		    set
		    {
		        this._bu = value;
		    }
		}
		
		private Empleado _empleado;
		public virtual Empleado Empleado 
		{ 
		    get
		    {
		        return this._empleado;
		    }
		    set
		    {
		        this._empleado = value;
		    }
		}
		
		private Rutum _rutum;
		public virtual Rutum Rutum 
		{ 
		    get
		    {
		        return this._rutum;
		    }
		    set
		    {
		        this._rutum = value;
		    }
		}
		
	}
}
