#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ORM_STM;


namespace ORM_STM	
{
	public partial class Rutum
	{
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private string _descripcion;
		public virtual string Descripcion 
		{ 
		    get
		    {
		        return this._descripcion;
		    }
		    set
		    {
		        this._descripcion = value;
		    }
		}
		
		private DateTime? _fecha_Creacion;
		public virtual DateTime? Fecha_creacion 
		{ 
		    get
		    {
		        return this._fecha_Creacion;
		    }
		    set
		    {
		        this._fecha_Creacion = value;
		    }
		}
		
		private bool? _estado;
		public virtual bool? Estado 
		{ 
		    get
		    {
		        return this._estado;
		    }
		    set
		    {
		        this._estado = value;
		    }
		}
		
		private IList<Programacion> _programacions = new List<Programacion>();
		public virtual IList<Programacion> Programacions 
		{ 
		    get
		    {
		        return this._programacions;
		    }
		}
		
	}
}
