#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ORM_STM;


namespace ORM_STM	
{
	public partial class Tarjetum
	{
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private int? _saldo;
		public virtual int? Saldo 
		{ 
		    get
		    {
		        return this._saldo;
		    }
		    set
		    {
		        this._saldo = value;
		    }
		}
		
		private bool? _estado;
		public virtual bool? Estado 
		{ 
		    get
		    {
		        return this._estado;
		    }
		    set
		    {
		        this._estado = value;
		    }
		}
		
		private int? _id_Estacion;
		public virtual int? Id_estacion 
		{ 
		    get
		    {
		        return this._id_Estacion;
		    }
		    set
		    {
		        this._id_Estacion = value;
		    }
		}
		
		private Estacion _estacion;
		public virtual Estacion Estacion 
		{ 
		    get
		    {
		        return this._estacion;
		    }
		    set
		    {
		        this._estacion = value;
		    }
		}
		
		private IList<Solicitud_reclamo> _solicitud_Reclamos = new List<Solicitud_reclamo>();
		public virtual IList<Solicitud_reclamo> Solicitud_reclamos 
		{ 
		    get
		    {
		        return this._solicitud_Reclamos;
		    }
		}
		
		private IList<Recarga> _recargas = new List<Recarga>();
		public virtual IList<Recarga> Recargas 
		{ 
		    get
		    {
		        return this._recargas;
		    }
		}
		
		private IList<Consumo> _consumos = new List<Consumo>();
		public virtual IList<Consumo> Consumos 
		{ 
		    get
		    {
		        return this._consumos;
		    }
		}
		
	}
}
