#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace ORM_STM	
{
	public partial class Tarjeta_personalizada
	{
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private int? _saldo;
		public virtual int? Saldo 
		{ 
		    get
		    {
		        return this._saldo;
		    }
		    set
		    {
		        this._saldo = value;
		    }
		}
		
		private bool? _estado;
		public virtual bool? Estado 
		{ 
		    get
		    {
		        return this._estado;
		    }
		    set
		    {
		        this._estado = value;
		    }
		}
		
		private int? _id_Estacion;
		public virtual int? Id_estacion 
		{ 
		    get
		    {
		        return this._id_Estacion;
		    }
		    set
		    {
		        this._id_Estacion = value;
		    }
		}
		
		private int? _id_Cliente;
		public virtual int? Id_cliente 
		{ 
		    get
		    {
		        return this._id_Cliente;
		    }
		    set
		    {
		        this._id_Cliente = value;
		    }
		}
		
		private string _nombre;
		public virtual string Nombre 
		{ 
		    get
		    {
		        return this._nombre;
		    }
		    set
		    {
		        this._nombre = value;
		    }
		}
		
		private string _telefono;
		public virtual string Telefono 
		{ 
		    get
		    {
		        return this._telefono;
		    }
		    set
		    {
		        this._telefono = value;
		    }
		}
		
	}
}
